[package]
name = "metorrent_common"
version = "0.1.0"
authors = ["Stacey Ell <stacey.ell@gmail.com>"]

[dependencies]
byteorder = "*"
serde = "*"
time = "*"
url = "*"
sha1 = "*"

[dependencies.bencode]
path = "../bencode"

[dependencies.metorrent_util]
path = "../util"
