name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: "rustup component add clippy && rustup component add rustfmt"
      - run: "cargo check"
      - run: "cargo build --verbose"
      - run: "RUST_BACKTRACE=1 cargo test --verbose"
      - run: "(cd magnetite && cargo check --no-default-features)"
      - run: "cargo fmt --all -- --check"
      - run: "cargo clippy --all-targets"
      # - run: "cargo audit"
